# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    image_resizer:
        class: AppBundle\Service\ImageResizer
    test_listener:
        class: AppBundle\Listener\TestListener
        tags:
            - {name: kernel.event_listener, event: kernel.response ,method: yo }
    custom_listener:
        class: AppBundle\Listener\CustomListener
        tags:
            - {name: kernel.event_listener, event: custom.test_event ,method: customHandler}
